const room_data = {
  floor1: [
    { floorNo: 1, roomNo: 101, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 1, roomNo: 102, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 1, roomNo: 103, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 1, roomNo: 104, status: "occupied", roomType: "Double", priorityScore: 73 },
    { floorNo: 1, roomNo: 105, status: "maintenance", roomType: "Single", priorityScore: null },
    { floorNo: 1, roomNo: 106, status: "empty", roomType: "Double", priorityScore: null },
    { floorNo: 1, roomNo: 107, status: "inspection", roomType: "Single", priorityScore: null },
  ],
  floor2: [
    { floorNo: 2, roomNo: 201, status: "occupied", roomType: "Single", priorityScore: 45 },
    { floorNo: 2, roomNo: 202, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 2, roomNo: 203, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 2, roomNo: 204, status: "inspection", roomType: "Single", priorityScore: null },
    { floorNo: 2, roomNo: 205, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 2, roomNo: 206, status: "empty", roomType: "Double", priorityScore: null },
    { floorNo: 2, roomNo: 207, status: "booked", roomType: "Single", priorityScore: 88 },
  ],
  floor3: [
    { floorNo: 3, roomNo: 301, status: "maintenance", roomType: "Double", priorityScore: null },
    { floorNo: 3, roomNo: 302, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 3, roomNo: 303, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 3, roomNo: 304, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 3, roomNo: 305, status: "occupied", roomType: "Double", priorityScore: 92 },
    { floorNo: 3, roomNo: 306, status: "inspection", roomType: "Single", priorityScore: null },
  ],
  floor4: [
    { floorNo: 4, roomNo: 401, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 4, roomNo: 402, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 4, roomNo: 403, status: "empty", roomType: "Single", priorityScore: null },
    { floorNo: 4, roomNo: 404, status: "occupied", roomType: "Double", priorityScore: 67 },
    { floorNo: 4, roomNo: 405, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 4, roomNo: 406, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 4, roomNo: 407, status: "maintenance", roomType: "Single", priorityScore: null },
  ],
  floor5: [
    { floorNo: 5, roomNo: 501, status: "inspection", roomType: "Double", priorityScore: null },
    { floorNo: 5, roomNo: 502, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 5, roomNo: 503, status: "occupied", roomType: "Double", priorityScore: 81 },
    { floorNo: 5, roomNo: 504, status: "empty", roomType: "Single", priorityScore: null },
    { floorNo: 5, roomNo: 505, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 5, roomNo: 506, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 5, roomNo: 507, status: "available", roomType: "Double", priorityScore: null },
  ],
  floor6: [
    { floorNo: 6, roomNo: 601, status: "empty", roomType: "Single", priorityScore: null },
    { floorNo: 6, roomNo: 602, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 6, roomNo: 603, status: "available", roomType: "Single", priorityScore: 55 },
    { floorNo: 6, roomNo: 604, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 6, roomNo: 605, status: "inspection", roomType: "Single", priorityScore: null },
    { floorNo: 6, roomNo: 606, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 6, roomNo: 607, status: "booked", roomType: "Single", priorityScore: 94 },
  ],
  floor7: [
    { floorNo: 7, roomNo: 701, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 7, roomNo: 702, status: "maintenance", roomType: "Single", priorityScore: null },
    { floorNo: 7, roomNo: 703, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 7, roomNo: 704, status: "empty", roomType: "Single", priorityScore: null },
    { floorNo: 7, roomNo: 705, status: "cleaning", roomType: "Double", priorityScore: 76 },
    { floorNo: 7, roomNo: 706, status: "available", roomType: "Single", priorityScore: null },
  ],
  floor8: [
    { floorNo: 8, roomNo: 801, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 8, roomNo: 802, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 8, roomNo: 803, status: "available", roomType: "Double", priorityScore: 63 },
    { floorNo: 8, roomNo: 804, status: "inspection", roomType: "Single", priorityScore: null },
    { floorNo: 8, roomNo: 805, status: "empty", roomType: "Double", priorityScore: null },
    { floorNo: 8, roomNo: 806, status: "available", roomType: "Single", priorityScore: null },
  ],
  floor9: [
    { floorNo: 9, roomNo: 901, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 9, roomNo: 902, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 9, roomNo: 903, status: "occupied", roomType: "Single", priorityScore: 89 },
    { floorNo: 9, roomNo: 904, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 9, roomNo: 905, status: "maintenance", roomType: "Single", priorityScore: null },
    { floorNo: 9, roomNo: 906, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 9, roomNo: 907, status: "empty", roomType: "Single", priorityScore: null },
  ],
  floor10: [
    { floorNo: 10, roomNo: 1001, status: "inspection", roomType: "Double", priorityScore: null },
    { floorNo: 10, roomNo: 1002, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 10, roomNo: 1003, status: "occupied", roomType: "Double", priorityScore: 71 },
    { floorNo: 10, roomNo: 1004, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 10, roomNo: 1005, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 10, roomNo: 1006, status: "empty", roomType: "Single", priorityScore: null },
  ],
};

export default room_data;