export default room_data = {
  floor1: [
    { floorNo: 1, roomNo: 1001, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 1, roomNo: 1002, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 1, roomNo: 1003, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 1, roomNo: 1004, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 1, roomNo: 1005, status: "checkout", roomType: "Single", priorityScore: 85 },
    { floorNo: 1, roomNo: 1006, status: "booked", roomType: "Double", priorityScore: null },
  ],
  floor2: [
    { floorNo: 2, roomNo: 2001, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 2, roomNo: 2002, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 2, roomNo: 2003, status: "checkout", roomType: "Double", priorityScore: 92 },
    { floorNo: 2, roomNo: 2004, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 2, roomNo: 2005, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 2, roomNo: 2006, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 2, roomNo: 2007, status: "inspection", roomType: "Single", priorityScore: null },
  ],
  floor3: [
    { floorNo: 3, roomNo: 3001, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 3, roomNo: 3002, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 3, roomNo: 3003, status: "checkout", roomType: "Double", priorityScore: 78 },
    { floorNo: 3, roomNo: 3004, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 3, roomNo: 3005, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 3, roomNo: 3006, status: "occupied", roomType: "Single", priorityScore: null },
  ],
  floor4: [
    { floorNo: 4, roomNo: 4001, status: "checkout", roomType: "Single", priorityScore: 95 },
    { floorNo: 4, roomNo: 4002, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 4, roomNo: 4003, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 4, roomNo: 4004, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 4, roomNo: 4005, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 4, roomNo: 4006, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 4, roomNo: 4007, status: "inspection", roomType: "Single", priorityScore: null },
  ],
  floor5: [
    { floorNo: 5, roomNo: 5001, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 5, roomNo: 5002, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 5, roomNo: 5003, status: "checkout", roomType: "Double", priorityScore: 88 },
    { floorNo: 5, roomNo: 5004, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 5, roomNo: 5005, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 5, roomNo: 5006, status: "occupied", roomType: "Single", priorityScore: null },
  ],
  floor6: [
    { floorNo: 6, roomNo: 6001, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 6, roomNo: 6002, status: "checkout", roomType: "Double", priorityScore: 70 },
    { floorNo: 6, roomNo: 6003, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 6, roomNo: 6004, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 6, roomNo: 6005, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 6, roomNo: 6006, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 6, roomNo: 6007, status: "inspection", roomType: "Single", priorityScore: null },
  ],
  floor7: [
    { floorNo: 7, roomNo: 7001, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 7, roomNo: 7002, status: "occupied", roomType: "Single", priorityScore: null },
    { floorNo: 7, roomNo: 7003, status: "checkout", roomType: "Double", priorityScore: 65 },
    { floorNo: 7, roomNo: 7004, status: "cleaning", roomType: "Single", priorityScore: null },
    { floorNo: 7, roomNo: 7005, status: "booked", roomType: "Double", priorityScore: null },
    { floorNo: 7, roomNo: 7006, status: "occupied", roomType: "Single", priorityScore: null },
  ],
  floor8: [
    { floorNo: 8, roomNo: 8001, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 8, roomNo: 8002, status: "checkout", roomType: "Single", priorityScore: 100 },
    { floorNo: 8, roomNo: 8003, status: "available", roomType: "Double", priorityScore: null },
    { floorNo: 8, roomNo: 8004, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 8, roomNo: 8005, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 8, roomNo: 8006, status: "occupied", roomType: "Single", priorityScore: null },
  ],
  floor9: [
    { floorNo: 9, roomNo: 9001, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 9, roomNo: 9002, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 9, roomNo: 9003, status: "checkout", roomType: "Single", priorityScore: 82 },
    { floorNo: 9, roomNo: 9004, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 9, roomNo: 9005, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 9, roomNo: 9006, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 9, roomNo: 9007, status: "inspection", roomType: "Single", priorityScore: null },
  ],
  floor10: [
    { floorNo: 10, roomNo: 10001, status: "occupied", roomType: "Double", priorityScore: null },
    { floorNo: 10, roomNo: 10002, status: "available", roomType: "Single", priorityScore: null },
    { floorNo: 10, roomNo: 10003, status: "checkout", roomType: "Double", priorityScore: 75 },
    { floorNo: 10, roomNo: 10004, status: "booked", roomType: "Single", priorityScore: null },
    { floorNo: 10, roomNo: 10005, status: "cleaning", roomType: "Double", priorityScore: null },
    { floorNo: 10, roomNo: 10006, status: "occupied", roomType: "Single", priorityScore: null },
  ],
};